/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalorieRouteImport } from './routes/calorie'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SmokingRouteImport } from './routes/smoking'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as WalkIndexRouteImport } from './routes/walk.index'
import { Route as WalkLogsRouteImport } from './routes/walk.logs'
import { Route as WalkNewRouteImport } from './routes/walk.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobUploadRouteImport } from './routes/api/blob/upload'
import { Route as ApiWalkImageRouteImport } from './routes/api/walk/image'
import { Route as WalkIdEditRouteImport } from './routes/walk.$id.edit'
import { Route as WalkLogsIndexRouteImport } from './routes/walk.logs.index'
import { Route as WalkLogsIdRouteImport } from './routes/walk.logs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalorieRoute = CalorieRouteImport.update({
  id: '/calorie',
  path: '/calorie',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SmokingRoute = SmokingRouteImport.update({
  id: '/smoking',
  path: '/smoking',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkIndexRoute = WalkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalkRoute,
} as any)
const WalkLogsRoute = WalkLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WalkRoute,
} as any)
const WalkNewRoute = WalkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WalkRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobUploadRoute = ApiBlobUploadRouteImport.update({
  id: '/api/blob/upload',
  path: '/api/blob/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalkImageRoute = ApiWalkImageRouteImport.update({
  id: '/api/walk/image',
  path: '/api/walk/image',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkIdEditRoute = WalkIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => WalkRoute,
} as any)
const WalkLogsIndexRoute = WalkLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalkLogsRoute,
} as any)
const WalkLogsIdRoute = WalkLogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WalkLogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calorie': typeof CalorieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password': typeof PasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smoking': typeof SmokingRoute
  '/walk': typeof WalkRouteWithChildren
  '/walk/logs': typeof WalkLogsRouteWithChildren
  '/walk/new': typeof WalkNewRoute
  '/walk/': typeof WalkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/walk/image': typeof ApiWalkImageRoute
  '/walk/$id/edit': typeof WalkIdEditRoute
  '/walk/logs/$id': typeof WalkLogsIdRoute
  '/walk/logs/': typeof WalkLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calorie': typeof CalorieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password': typeof PasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smoking': typeof SmokingRoute
  '/walk/new': typeof WalkNewRoute
  '/walk': typeof WalkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/walk/image': typeof ApiWalkImageRoute
  '/walk/$id/edit': typeof WalkIdEditRoute
  '/walk/logs/$id': typeof WalkLogsIdRoute
  '/walk/logs': typeof WalkLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calorie': typeof CalorieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/password': typeof PasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smoking': typeof SmokingRoute
  '/walk': typeof WalkRouteWithChildren
  '/walk/logs': typeof WalkLogsRouteWithChildren
  '/walk/new': typeof WalkNewRoute
  '/walk/': typeof WalkIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/upload': typeof ApiBlobUploadRoute
  '/api/walk/image': typeof ApiWalkImageRoute
  '/walk/$id/edit': typeof WalkIdEditRoute
  '/walk/logs/$id': typeof WalkLogsIdRoute
  '/walk/logs/': typeof WalkLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calorie'
    | '/forgot-password'
    | '/login'
    | '/password'
    | '/reset-password'
    | '/smoking'
    | '/walk'
    | '/walk/logs'
    | '/walk/new'
    | '/walk/'
    | '/api/auth/$'
    | '/api/blob/upload'
    | '/api/walk/image'
    | '/walk/$id/edit'
    | '/walk/logs/$id'
    | '/walk/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calorie'
    | '/forgot-password'
    | '/login'
    | '/password'
    | '/reset-password'
    | '/smoking'
    | '/walk/new'
    | '/walk'
    | '/api/auth/$'
    | '/api/blob/upload'
    | '/api/walk/image'
    | '/walk/$id/edit'
    | '/walk/logs/$id'
    | '/walk/logs'
  id:
    | '__root__'
    | '/'
    | '/calorie'
    | '/forgot-password'
    | '/login'
    | '/password'
    | '/reset-password'
    | '/smoking'
    | '/walk'
    | '/walk/logs'
    | '/walk/new'
    | '/walk/'
    | '/api/auth/$'
    | '/api/blob/upload'
    | '/api/walk/image'
    | '/walk/$id/edit'
    | '/walk/logs/$id'
    | '/walk/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalorieRoute: typeof CalorieRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PasswordRoute: typeof PasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SmokingRoute: typeof SmokingRoute
  WalkRoute: typeof WalkRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobUploadRoute: typeof ApiBlobUploadRoute
  ApiWalkImageRoute: typeof ApiWalkImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calorie': {
      id: '/calorie'
      path: '/calorie'
      fullPath: '/calorie'
      preLoaderRoute: typeof CalorieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoking': {
      id: '/smoking'
      path: '/smoking'
      fullPath: '/smoking'
      preLoaderRoute: typeof SmokingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/': {
      id: '/walk/'
      path: '/'
      fullPath: '/walk/'
      preLoaderRoute: typeof WalkIndexRouteImport
      parentRoute: typeof WalkRoute
    }
    '/walk/logs': {
      id: '/walk/logs'
      path: '/logs'
      fullPath: '/walk/logs'
      preLoaderRoute: typeof WalkLogsRouteImport
      parentRoute: typeof WalkRoute
    }
    '/walk/new': {
      id: '/walk/new'
      path: '/new'
      fullPath: '/walk/new'
      preLoaderRoute: typeof WalkNewRouteImport
      parentRoute: typeof WalkRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/upload': {
      id: '/api/blob/upload'
      path: '/api/blob/upload'
      fullPath: '/api/blob/upload'
      preLoaderRoute: typeof ApiBlobUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/walk/image': {
      id: '/api/walk/image'
      path: '/api/walk/image'
      fullPath: '/api/walk/image'
      preLoaderRoute: typeof ApiWalkImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/$id/edit': {
      id: '/walk/$id/edit'
      path: '/$id/edit'
      fullPath: '/walk/$id/edit'
      preLoaderRoute: typeof WalkIdEditRouteImport
      parentRoute: typeof WalkRoute
    }
    '/walk/logs/': {
      id: '/walk/logs/'
      path: '/'
      fullPath: '/walk/logs/'
      preLoaderRoute: typeof WalkLogsIndexRouteImport
      parentRoute: typeof WalkLogsRoute
    }
    '/walk/logs/$id': {
      id: '/walk/logs/$id'
      path: '/$id'
      fullPath: '/walk/logs/$id'
      preLoaderRoute: typeof WalkLogsIdRouteImport
      parentRoute: typeof WalkLogsRoute
    }
  }
}

interface WalkLogsRouteChildren {
  WalkLogsIdRoute: typeof WalkLogsIdRoute
  WalkLogsIndexRoute: typeof WalkLogsIndexRoute
}

const WalkLogsRouteChildren: WalkLogsRouteChildren = {
  WalkLogsIdRoute: WalkLogsIdRoute,
  WalkLogsIndexRoute: WalkLogsIndexRoute,
}

const WalkLogsRouteWithChildren = WalkLogsRoute._addFileChildren(
  WalkLogsRouteChildren,
)

interface WalkRouteChildren {
  WalkLogsRoute: typeof WalkLogsRouteWithChildren
  WalkNewRoute: typeof WalkNewRoute
  WalkIndexRoute: typeof WalkIndexRoute
  WalkIdEditRoute: typeof WalkIdEditRoute
}

const WalkRouteChildren: WalkRouteChildren = {
  WalkLogsRoute: WalkLogsRouteWithChildren,
  WalkNewRoute: WalkNewRoute,
  WalkIndexRoute: WalkIndexRoute,
  WalkIdEditRoute: WalkIdEditRoute,
}

const WalkRouteWithChildren = WalkRoute._addFileChildren(WalkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalorieRoute: CalorieRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PasswordRoute: PasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SmokingRoute: SmokingRoute,
  WalkRoute: WalkRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobUploadRoute: ApiBlobUploadRoute,
  ApiWalkImageRoute: ApiWalkImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
